### ISSUE TITLE
Serial device is not connected even though the system recognizes it

### ISSUE THREAD

**Issue by ranstlouis** [cbteeple/pressure_control_cbt#5]
## Expected Behavior
Serial device is connected as a pressure controller. When you run "find_serial" command, the device shows up, but still doesn't get connected.

### hardware config:
```yaml
# ROS node settings
traj_server_rate: 20 # Should be < 40 Hz for serial comms
data_channel: "dynamixel"
use_traj_server: True

# Serial device info
devices:
  - devname: /dev/ttyUSB0
    baudrate: 9600 #115200
    num_channels: 1
    cmd_spec: '2.2'
    cmd_format: '%0.2f'
```

## Actual Behavior
Error: `Exception: Comms were not connected for device #0 in the list`

```bash
roslaunch pressure_controller_ros bringup_HID.launch profile:=dynamixel_single hw_profile:=dynamixel_default debug:=true
... logging to /home/ranstlouis/.ros/log/e8ecb780-5c3e-11ec-9096-0800270d18c9/roslaunch-ranstlouis-VirtualBox-7142.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ranstlouis-VirtualBox:36225/

SUMMARY
========

PARAMETERS
 * /config_node/DEBUG: True
 * /config_node/PID/all_equal: True
 * /config_node/PID/values: [0.09, 1.5, 0]
 * /config_node/channels/num_channels: 1
 * /config_node/channels/states: [1]
 * /config_node/data_loop_time: 50
 * /config_node/echo: False
 * /config_node/gui/groups: [[0, 1], [2, 3]]
 * /config_node/max_pressure: 90
 * /config_node/min_pressure: 0
 * /config_node/profile_name: dynamixel_single
 * /pressure_control_server_node/DEBUG: True
 * /pressure_control_server_node/data_channel: dynamixel
 * /pressure_control_server_node/devices: [{'devname': '/de...
 * /pressure_control_server_node/traj_server_rate: 200.0
 * /pressure_control_server_node/use_traj_server: True
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /setpoint_server_node/DEBUG: True

NODES
  /
    config_node (pressure_controller_ros/config.py)
    console (rqt_console/rqt_console)
    pressure_control_server_node (pressure_controller_ros/comm_handler.py)
    pressure_plot (rqt_multiplot/rqt_multiplot)
    setpoint_server_node (pressure_controller_ros/setpoint_server.py)

ROS_MASTER_URI=http://localhost:11311

process[pressure_plot-1]: started with pid [7157]
process[console-2]: started with pid [7158]
process[pressure_control_server_node-3]: started with pid [7159]
process[config_node-4]: started with pid [7160]
process[setpoint_server_node-5]: started with pid [7161]
SETPOINT SERVER: Node Initiatilized (/setpoint_server_node)
HW INTERFACE: Node Initiatilized (/pressure_control_server_node/dynamixel)
SERIAL ERROR: Maybe the device is unplugged?
<pressure_controller_ros.hardware_interface.serial_coms.SerialComs instance at 0x7f0528886550>
Traceback (most recent call last):
  File "/home/ranstlouis/catkin_ws/src/pressure_control_cbt/pressure_controller_ros/scripts/hw_interface/comm_handler.py", line 351, in <module>
    server = CommHandler(rospy.get_name())
  File "/home/ranstlouis/catkin_ws/src/pressure_control_cbt/pressure_controller_ros/scripts/hw_interface/comm_handler.py", line 75, in __init__
    raise Exception("Comms were not connected for device #%d in the list"%(idx))
Exception: Comms were not connected for device #0 in the list

```

## Steps to Reproduce the Problem

  1. Install package + run example script "bringup_HID.launch"
  2. It fails.

## Specifications

  - Version: 
  - Platform: Ubuntu 18.04
  - Subsystem:

**Comment by ranstlouis** [comment]
Rosparam for the devices is correct:

```
rosparam get /pressure_control_server_node/devices

- {baudrate: 9600, cmd_format: '%0.2f', cmd_spec: '2.2', devname: /dev/ttyUSB0, num_channels: 1}
```

**Comment by ranstlouis** [comment]
Solved with: ``sudo adduser second_user dialout``
